# Generated by Django 5.0.4 on 2024-07-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entidadesFinancieras2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=70)),
                ('localidad', models.CharField(max_length=100)),
                ('tipo_tenencia', models.CharField(max_length=50)),
                ('tipo_persona', models.CharField(max_length=30)),
                ('num_credito', models.IntegerField()),
                ('num_cliente', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('representante_legal', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=12)),
                ('producto_tipoCredito', models.CharField(max_length=40)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodo_pago', models.CharField(max_length=50)),
                ('monto_garantiasLiquidasVigente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_garantias', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_garantiaLiquidaEjercida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_disponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_recuperado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inclumplimiento_credito', models.CharField(max_length=100)),
                ('intermediario_financiero', models.CharField(max_length=150)),
                ('tipo_concepto', models.CharField(max_length=30)),
                ('descripcion_concepto', models.TextField()),
                ('beneficiarios_hombres', models.IntegerField()),
                ('beneficiarios_mujer', models.IntegerField()),
                ('total_beneficiarios', models.IntegerField()),
                ('empleos_directos', models.IntegerField()),
                ('empleos_indirectos', models.IntegerField()),
                ('subsector', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('variedad', models.CharField(max_length=50)),
                ('cultivo', models.CharField(max_length=40)),
                ('superficie', models.CharField(max_length=40)),
                ('volumen_produccion_anual', models.IntegerField()),
                ('tipo_mercado', models.CharField(max_length=50)),
                ('producto_comercializa', models.CharField(max_length=50)),
            ],
        ),
    ]
