# Generated by Django 5.0.4 on 2024-11-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_entidadesfinancieras2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidadesfinancieras2',
            name='region',
        ),
        migrations.AddField(
            model_name='municipios',
            name='ciit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='municipios',
            name='e_cien',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='municipios',
            name='pueblo_indigena',
            field=models.CharField(default='Mixteco', max_length=100),
        ),
        migrations.AddField(
            model_name='municipios',
            name='region',
            field=models.CharField(default='valles centrales', max_length=100),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.municipios'),
        ),
    ]
