# Generated by Django 5.0.4 on 2024-11-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_entidadesfinancieras2_region_municipios_ciit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='entidadesFinancieras',
        ),
    ]
