# Generated by Django 5.0.4 on 2024-11-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_delete_entidadesfinancieras'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='municipios',
            new_name='municipios2',
        ),
    ]
