# Generated by Django 5.0.4 on 2024-11-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_rename_municipios_municipios2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='municipios2',
            new_name='municipios',
        ),
    ]
