# Generated by Django 5.0.4 on 2024-11-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_rename_municipios2_municipios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipios',
            old_name='e_cien',
            new_name='eCien',
        ),
        migrations.RenameField(
            model_name='municipios',
            old_name='pueblo_indigena',
            new_name='puebloIndigena',
        ),
    ]
