# Generated by Django 5.0.4 on 2024-11-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_entidadesfinancieras2_aportacion_productor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='aportacion_productor',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='beneficiarios_hombres',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='beneficiarios_mujer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='descripcion_concepto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='empleos_directos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='empleos_indirectos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='inclumplimiento_credito',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='monto_garantiaLiquidaEjercida',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='monto_garantiasLiquidasVigente',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='monto_recuperado',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='num_cliente',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='num_credito',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='periodo_pago',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='porcentaje_garantias',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='producto_comercializa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='producto_tipoCredito',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='telefono',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='tipo_concepto',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='tipo_mercado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='tipo_tenencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='total_beneficiarios',
            field=models.IntegerField(null=True),
        ),
    ]
