# Generated by Django 5.0.4 on 2024-12-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_alter_entidadesfinancieras2_aportacion_productor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='monto_total',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
    ]
