# Generated by Django 5.0.4 on 2024-12-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_alter_entidadesfinancieras2_intermediario_financiero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='fecha_termino',
            field=models.DateField(null=True),
        ),
    ]
