# Generated by Django 5.0.4 on 2024-12-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_alter_entidadesfinancieras2_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='aportacion_productor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='beneficiarios_hombres',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='beneficiarios_mujer',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='empleos_directos',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='empleos_indirectos',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='fecha_inicio',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='fecha_termino',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='monto_garantiaLiquidaEjercida',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='monto_garantiasLiquidasVigente',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='monto_recuperado',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='num_cliente',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='num_credito',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='porcentaje_garantias',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='saldo_disponible',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='tasa_interes',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='total_beneficiarios',
            field=models.IntegerField(blank=True),
        ),
    ]
