# Generated by Django 5.0.4 on 2024-12-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_alter_entidadesfinancieras2_aportacion_productor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
