# Generated by Django 5.0.4 on 2024-12-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_alter_entidadesfinancieras2_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='puebloIndigena',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
