# Generated by Django 5.0.4 on 2025-01-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_alter_entidadesfinancieras2_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadesfinancieras2',
            name='intermediario_financiero_FIRA',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
