# Generated by Django 5.0.4 on 2025-01-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_entidadesfinancieras2_intermediario_financiero_fira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='num_credito',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='producto_tipoCredito',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
