# Generated by Django 5.0.4 on 2025-02-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_alter_entidadesfinancieras2_num_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadesfinancieras2',
            name='tecnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='tipo_concepto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
