# Generated by Django 5.0.4 on 2025-02-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_alter_entidadesfinancieras2_tipo_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadesfinancieras2',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
