# Generated by Django 5.0.4 on 2025-02-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0025_entidadesfinancieras2_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='tasa_interes',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
    ]
