# Generated by Django 5.0.4 on 2025-02-12 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0026_alter_entidadesfinancieras2_tasa_interes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidades', to='form.municipios'),
        ),
    ]
