# Generated by Django 5.0.4 on 2025-02-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0027_alter_entidadesfinancieras2_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='num_credito',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='porcentaje_garantias',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
