# Generated by Django 5.0.4 on 2025-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0028_alter_entidadesfinancieras2_num_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='producto_comercializa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
