# Generated by Django 5.0.4 on 2025-02-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0029_alter_entidadesfinancieras2_producto_comercializa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='volumen_produccion_anual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
