# Generated by Django 5.0.4 on 2025-02-17 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_alter_entidadesfinancieras2_volumen_produccion_anual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProductor', models.CharField(blank=True, max_length=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('nombreProducto', models.CharField(blank=True, max_length=100, null=True)),
                ('nombreMarca', models.CharField(blank=True, max_length=100, null=True)),
                ('subsector', models.CharField(blank=True, max_length=50, null=True)),
                ('volumen_produccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('imagenProd', models.ImageField(default='IMAGEN PRODUCTO', upload_to='imagenes/')),
                ('estado', models.BooleanField(default=False)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='form.municipios')),
            ],
        ),
    ]
