# Generated by Django 5.0.4 on 2025-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0031_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
    ]
