# Generated by Django 5.0.4 on 2025-02-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_alter_entidadesfinancieras2_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadesfinancieras2',
            name='aportacion_productor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True),
        ),
    ]
