# Generated by Django 5.0.4 on 2025-02-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0034_alter_entidadesfinancieras2_aportacion_productor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
