# Generated by Django 5.0.4 on 2025-05-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0036_productos_disponibilidad_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
