# Generated by Django 5.0.4 on 2025-06-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0037_productos_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='comentarios',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='unidad_medidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
