# Generated by Django 5.0.4 on 2026-02-20 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0038_productos_comentarios_productos_unidad_medidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAbasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto_abasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='form.productoabasto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
