# Generated by Django 5.0.4 on 2026-02-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0039_productoabasto_historialprecio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=150)),
                ('calidad', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=150)),
                ('precio_frec', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField()),
            ],
            options={
                'unique_together': {('producto', 'calidad', 'presentacion', 'fecha')},
            },
        ),
    ]
