# Generated by Django 5.0.4 on 2026-03-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0040_precioagricola'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioGrano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=150)),
                ('calidad', models.CharField(max_length=150, verbose_name='Origen')),
                ('presentacion', models.CharField(max_length=150)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('producto', 'calidad', 'presentacion', 'fecha_registro')},
            },
        ),
    ]
