
from django.contrib import admin
from django.urls import path, include
from form import views 
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.signin, name='login'),
    path('home/', views.home, name='home' ),
    path('gestionProductos/', views.gestProd, name='gestionProductos' ),
    path('form/', views.form, name='form' ),
    path('logout/', views.signout, name='logout'),
    path('reporte/', views.reporte, name='reporte'),
    path('grafica/', views.graficas, name='grafica'),
    path('graficaPubli/', views.graficasPublicas, name='graficaPubli'),
    path('getcharts/', views.get_chart, name='getcharts'),
    path('getcharts2/', views.get_chart2, name='getcharts2'),
    path('getcharts22023/', views.get_chart22023, name='getcharts22023'),
    path('getcharts3/', views.get_chart3, name='getcharts3'),
    path('getcharts4/', views.get_chart4, name='getcharts4'),
    path('getcharts5/', views.get_chart5, name='getcharts5'),
    path('get_chart_2023_1/', views.get_chart_2023_1, name='get_chart_2023_1'),
    path('get_chart_2024_1/', views.get_chart_2024_1, name='get_chart_2024_1'),
    path('get_chart_2023_2/', views.get_chart22023, name='get_chart_2023_2'),
    path('get_chart_2024_2/', views.get_chart22024, name='get_chart_2024_2'),
    path('get_chart_2023_3/', views.get_chart32023, name='get_chart_2023_3'),
    path('get_chart_2024_3/', views.get_chart32024, name='get_chart_2024_3'),

    path('get_chart_2023_5/', views.get_chart52023, name='get_chart_2023_5'),
    path('get_chart_2024_5/', views.get_chart52024, name='get_chart_2024_5'),

    path('tiendaHome/', views.tiendaIndex, name='tiendaHome'),
    path('categoriaAgricola/', views.tiendaAgricola, name='categoriaAgricola'),
    path('categoriaPecuario/', views.tiendaPecuario, name='categoriaPecuario'),
    path('categoriaPesquero/', views.tiendaPesquero, name='categoriaPesquero'),
    path('categoriaAcuicola/', views.tiendaAcuicola, name='categoriaAcuicola'),
    path('categoriaForestal/', views.tiendaForestal, name='categoriaForestal'),
    path('categoriaAgroindustrial/', views.tiendaIndustrial, name='categoriaAgroindustrial'),
    path('productosAgricola/<str:categoria>/', views.tiendaProducAgri, name="productosAgricola"),
    path('productosPecuario/<str:categoria>/', views.tiendaProducPecu, name="productosPecuario"),
    path('detailProduct/<int:product_id>/', views.prodDetail, name='detailProduct'),
    path('formProductos/', views.formProductos, name='formProductos' ),
    path('credit/<int:credit_id>/', views.creditDetail, name='creditDetail'),
    
    path('product/<int:prod_id>/approved', views.productApproved, name='productApproved'),
    path('product/<int:prodA_id>/desapproved', views.productDesapproved, name='productDesapproved'),
    path('credit/<int:credit_id>/update', views.creditUpdate, name='creditUpdate'),
    path('eliminar/<int:id>/', views.delete_credit, name='delete_credit'),
    path('', views.indSec, name='index' ),
    path('agricola/', views.sectorAgri, name='agricola'),
    path('descripcion_agave/', TemplateView.as_view(template_name="agave/descripcion_agave.html"), name='descripcion_agave'),
    path('tablas2/', TemplateView.as_view(template_name="agave/tablas/2.html"), name='tablas2'),
    path('tablas3/', TemplateView.as_view(template_name="agave/tablas/3.html"), name='tablas3'),
    path('tablas4/', TemplateView.as_view(template_name="agave/tablas/4.html"), name='tablas4'),
    path('tablas5/', TemplateView.as_view(template_name="agave/tablas/5.html"), name='tablas5'),
    path('grafica1/', TemplateView.as_view(template_name="agave/graficas/grafica1.html"), name='grafica1'),
    path('tablas6/', TemplateView.as_view(template_name="agave/tablas/6.html"), name='tablas6'),
    path('grafica2/', TemplateView.as_view(template_name="agave/graficas/grafica2.html"), name='grafica2'),
    path('grafica3/', TemplateView.as_view(template_name="agave/graficas/grafica3.html"), name='grafica3'),
    path('tablas8/', TemplateView.as_view(template_name="agave/tablas/8.html"), name='tablas8'),
    path('iframeAgave/', TemplateView.as_view(template_name="agave/iframe_de_todo.html"), name='iframeAgave'),
    path('agave/', TemplateView.as_view(template_name="agave/estadisticas_agave.html"), name='agave'),
    path('mapa/', TemplateView.as_view(template_name="agave/mapa.html"), name='mapa'),
    path('descripcion_ajonjoli/', TemplateView.as_view(template_name="ajonjoli/descripcion_ajonjoli.html"), name='descripcion_ajonjoli'),
    path('tablas1Aj/', TemplateView.as_view(template_name="ajonjoli/tablas/1.html"), name='tablas1Aj'),
    path('tablas2Aj/', TemplateView.as_view(template_name="ajonjoli/tablas/2.html"), name='tablas2Aj'),
    path('tablas3Aj/', TemplateView.as_view(template_name="ajonjoli/tablas/3.html"), name='tablas3Aj'),
    path('tablas4Aj/', TemplateView.as_view(template_name="ajonjoli/tablas/4.html"), name='tablas4Aj'),
    path('graficas1Aj/', TemplateView.as_view(template_name="ajonjoli/graficas/1.html"), name='graficas1Aj'),
    path('graficas2Aj/', TemplateView.as_view(template_name="ajonjoli/graficas/2.html"), name='graficas2Aj'),
    path('graficas3Aj/', TemplateView.as_view(template_name="ajonjoli/graficas/3.html"), name='graficas3Aj'),
    path('graficas4Aj/', TemplateView.as_view(template_name="ajonjoli/graficas/4.html"), name='graficas4Aj'),
    path('tablas5Aj/', TemplateView.as_view(template_name="ajonjoli/tablas/5.html"), name='tablas5Aj'),
    path('mapa3Aj/', TemplateView.as_view(template_name="ajonjoli/tablas/mapa3.html"), name='mapa3Aj'),
    path('iframeAjonjoli/', TemplateView.as_view(template_name="ajonjoli/iframe_de_todo.html"), name='iframeAjonjoli'),
    path('ajonjoli/', TemplateView.as_view(template_name="ajonjoli/estadisticas_ajonjoli.html"), name='ajonjoli'),
    path('descripcion_calabacita/', TemplateView.as_view(template_name="calabacita/descripcion_calabacita.html"), name='descripcion_calabacita'),
    path('tablas1Ca/', TemplateView.as_view(template_name="calabacita/tablas/1.html"), name='tablas1Ca'),
    path('tablas2Ca/', TemplateView.as_view(template_name="calabacita/tablas/2.html"), name='tablas2Ca'),
    path('tablas3Ca/', TemplateView.as_view(template_name="calabacita/tablas/3.html"), name='tablas3Ca'),
    path('graficas1Ca/', TemplateView.as_view(template_name="calabacita/graficas/1.html"), name='graficas1Ca'),
    path('graficas2Ca/', TemplateView.as_view(template_name="calabacita/graficas/2.html"), name='graficas2Ca'),
    path('tablas4Ca/', TemplateView.as_view(template_name="calabacita/tablas/4.html"), name='tablas4Ca'),
    path('graficas3Ca/', TemplateView.as_view(template_name="calabacita/graficas/3.html"), name='graficas3Ca'),
    path('graficas4Ca/', TemplateView.as_view(template_name="calabacita/graficas/4.html"), name='graficas4Ca'),
    path('tablas5Ca/', TemplateView.as_view(template_name="calabacita/tablas/5.html"), name='tablas5Ca'),
    path('iframeCalabacita/', TemplateView.as_view(template_name="calabacita/iframe_de_todo.html"), name='iframeCalabacita'),
    path('calabacita/', TemplateView.as_view(template_name="calabacita/estadisticas_calabacita.html"), name='calabacita'),
    path('descripcion_cafe/', TemplateView.as_view(template_name="cafe/descripcion_cafe.html"), name='descripcion_cafe'),
    path('tablas1Caf/', TemplateView.as_view(template_name="cafe/tablas/1.html"), name='tablas1Caf'),
    path('tablas2Caf/', TemplateView.as_view(template_name="cafe/tablas/2.html"), name='tablas2Caf'),
    path('tablas3Caf/', TemplateView.as_view(template_name="cafe/tablas/3.html"), name='tablas3Caf'),
    path('graficas1Caf/', TemplateView.as_view(template_name="cafe/graficas/1.html"), name='graficas1Caf'),
    path('graficas2Caf/', TemplateView.as_view(template_name="cafe/graficas/2.html"), name='graficas2Caf'),
    path('tablas4Caf/', TemplateView.as_view(template_name="cafe/tablas/4.html"), name='tablas4Caf'),
    path('graficas3Caf/', TemplateView.as_view(template_name="cafe/graficas/3.html"), name='graficas3Caf'),
    path('graficas4Caf/', TemplateView.as_view(template_name="cafe/graficas/4.html"), name='graficas4Caf'),
    path('tablas5Caf/', TemplateView.as_view(template_name="cafe/tablas/5.html"), name='tablas5Caf'),
    path('iframeCafe/', TemplateView.as_view(template_name="cafe/iframe_de_todo.html"), name='iframeCafe'),
    path('cafe/', TemplateView.as_view(template_name="cafe/estadisticas_cafe.html"), name='cafe'),
    path('descripcion_jengibre/', TemplateView.as_view(template_name="jengibre/descripcion_jengibre.html"), name='descripcion_jengibre'),
    path('tablas1Jen/', TemplateView.as_view(template_name="jengibre/tablas/1.html"), name='tablas1Jen'),
    path('tablas2Jen/', TemplateView.as_view(template_name="jengibre/tablas/2.html"), name='tablas2Jen'),
    path('tablas3Jen/', TemplateView.as_view(template_name="jengibre/tablas/3.html"), name='tablas3Jen'),
    path('graficas1Jen/', TemplateView.as_view(template_name="jengibre/graficas/1.html"), name='graficas1Jen'),
    path('graficas2Jen/', TemplateView.as_view(template_name="jengibre/graficas/2.html"), name='graficas2Jen'),
    path('tablas5Jen/', TemplateView.as_view(template_name="jengibre/tablas/5.html"), name='tablas5Jen'),
    path('graficas3Jen/', TemplateView.as_view(template_name="jengibre/graficas/3.html"), name='graficas3Jen'),
    path('tablas6Jen/', TemplateView.as_view(template_name="jengibre/tablas/6.html"), name='tablas6Jen'),
    path('iframeJengibre/', TemplateView.as_view(template_name="jengibre/iframe_de_todo.html"), name='iframeJengibre'),
    path('jengibre/', TemplateView.as_view(template_name="jengibre/estadisticas_jengibre.html"), name='jengibre'),
    path('descripcion_limon/', TemplateView.as_view(template_name="limon/descripcion_limon.html"), name='descripcion_limon'),
    path('tablas1Li/', TemplateView.as_view(template_name="limon/tablas/1.html"), name='tablas1Li'),
    path('tablas2Li/', TemplateView.as_view(template_name="limon/tablas/2.html"), name='tablas2Li'),
    path('tablas3Li/', TemplateView.as_view(template_name="limon/tablas/3.html"), name='tablas3Li'),
    path('graficas1Li/', TemplateView.as_view(template_name="limon/graficas/1.html"), name='graficas1Li'),
    path('graficas2Li/', TemplateView.as_view(template_name="limon/graficas/2.html"), name='graficas2Li'),
    path('tablas5Li/', TemplateView.as_view(template_name="limon/tablas/5.html"), name='tablas5Li'),
    path('graficas3Li/', TemplateView.as_view(template_name="limon/graficas/3.html"), name='graficas3Li'),
    path('graficas4Li/', TemplateView.as_view(template_name="limon/graficas/4.html"), name='graficas4Li'),
    path('tablas6Li/', TemplateView.as_view(template_name="limon/tablas/6.html"), name='tablas6Li'),
    path('iframeLimon/', TemplateView.as_view(template_name="limon/iframe_de_todo.html"), name='iframeLimon'),
    path('limon/', TemplateView.as_view(template_name="limon/estadisticas_limon.html"), name='limon'),
    path('descripcion_litchi/', TemplateView.as_view(template_name="litchi/descripcion_litchi.html"), name='descripcion_litchi'),
    path('tablas1Lt/', TemplateView.as_view(template_name="litchi/tablas/1.html"), name='tablas1Lt'),
    path('graficas1Lt/', TemplateView.as_view(template_name="litchi/graficas/1.html"), name='graficas1Lt'),
    path('tablas3Lt/', TemplateView.as_view(template_name="litchi/tablas/3.html"), name='tablas3Lt'),
    path('graficas2Lt/', TemplateView.as_view(template_name="litchi/graficas/2.html"), name='graficas2Lt'),
    path('tablas4Lt/', TemplateView.as_view(template_name="litchi/tablas/4.html"), name='tablas4Lt'),
    path('iframeLitchi/', TemplateView.as_view(template_name="litchi/iframe_de_todo.html"), name='iframeLitchi'),
    path('litchi/', TemplateView.as_view(template_name="litchi/estadisticas_litchi.html"), name='litchi'),
    path('descripcion_mango/', TemplateView.as_view(template_name="mango/descripcion_mango.html"), name='descripcion_mango'),
    path('tablas1Man/', TemplateView.as_view(template_name="mango/tablas/1.html"), name='tablas1Man'),
    path('tablas2Man/', TemplateView.as_view(template_name="mango/tablas/2.html"), name='tablas2Man'),
    path('tablas3Man/', TemplateView.as_view(template_name="mango/tablas/3.html"), name='tablas3Man'),
    path('graficas1Man/', TemplateView.as_view(template_name="mango/graficas/1.html"), name='graficas1Man'),
    path('graficas2Man/', TemplateView.as_view(template_name="mango/graficas/2.html"), name='graficas2Man'),
    path('tablas5Man/', TemplateView.as_view(template_name="mango/tablas/5.html"), name='tablas5Man'),
    path('graficas3Man/', TemplateView.as_view(template_name="mango/graficas/3.html"), name='graficas3Man'),
    path('graficas4Man/', TemplateView.as_view(template_name="mango/graficas/4.html"), name='graficas4Man'),
    path('tablas6Man/', TemplateView.as_view(template_name="mango/tablas/6.html"), name='tablas6Man'),
    path('iframeMango/', TemplateView.as_view(template_name="mango/iframe_de_todo.html"), name='iframeMango'),
    path('mango/', TemplateView.as_view(template_name="mango/estadisticas_mango.html"), name='mango'),
    path('descripcion_melon/', TemplateView.as_view(template_name="melon/descripcion_melon.html"), name='descripcion_melon'),
    path('tablas1Me/', TemplateView.as_view(template_name="melon/tablas/1.html"), name='tablas1Me'),
    path('tablas2Me/', TemplateView.as_view(template_name="melon/tablas/2.html"), name='tablas2Me'),
    path('tablas3Me/', TemplateView.as_view(template_name="melon/tablas/3.html"), name='tablas3Me'),
    path('tablas4Me/', TemplateView.as_view(template_name="melon/tablas/4.html"), name='tablas4Me'),
    path('graficas1Me/', TemplateView.as_view(template_name="melon/graficas/1.html"), name='graficas1Me'),
    path('graficas2Me/', TemplateView.as_view(template_name="melon/graficas/2.html"), name='graficas2Me'),
    path('tablas5Me/', TemplateView.as_view(template_name="melon/tablas/5.html"), name='tablas5Me'),
    path('graficas3Me/', TemplateView.as_view(template_name="melon/graficas/3.html"), name='graficas3Me'),
    path('graficas4Me/', TemplateView.as_view(template_name="melon/graficas/4.html"), name='graficas4Me'),
    path('tablas6Me/', TemplateView.as_view(template_name="melon/tablas/6.html"), name='tablas6Me'),
    path('iframeMe/', TemplateView.as_view(template_name="melon/iframe_de_todo.html"), name='iframeMe'),
    path('melon/', TemplateView.as_view(template_name="melon/estadisticas_melon.html"), name='melon'),
    path('descripcion_papaya/', TemplateView.as_view(template_name="papaya/descripcion_papaya.html"), name='descripcion_papaya'),
    path('tablas1Pa/', TemplateView.as_view(template_name="papaya/tablas/1.html"), name='tablas1Pa'),
    path('tablas2Pa/', TemplateView.as_view(template_name="papaya/tablas/2.html"), name='tablas2Pa'),
    path('tablas3Pa/', TemplateView.as_view(template_name="papaya/tablas/3.html"), name='tablas3Pa'),
    path('graficas1Pa/', TemplateView.as_view(template_name="papaya/graficas/1.html"), name='graficas1Pa'),
    path('graficas2Pa/', TemplateView.as_view(template_name="papaya/graficas/2.html"), name='graficas2Pa'),
    path('tablas4Pa/', TemplateView.as_view(template_name="papaya/tablas/4.html"), name='tablas4Pa'),
    path('tablas5Pa/', TemplateView.as_view(template_name="papaya/tablas/5.html"), name='tablas5Pa'),
    path('graficas3Pa/', TemplateView.as_view(template_name="papaya/graficas/3.html"), name='graficas3Pa'),
    path('graficas4Pa/', TemplateView.as_view(template_name="papaya/graficas/4.html"), name='graficas4Pa'),
    path('iframePa/', TemplateView.as_view(template_name="papaya/iframe_de_todo.html"), name='iframePa'),
    path('papaya/', TemplateView.as_view(template_name="papaya/estadisticas_papaya.html"), name='papaya'),
    path('descripcion_pepino/', TemplateView.as_view(template_name="pepino/descripcion_pepino.html"), name='descripcion_pepino'),
    path('tablas1Pep/', TemplateView.as_view(template_name="pepino/tablas/1.html"), name='tablas1Pep'),
    path('tablas2Pep/', TemplateView.as_view(template_name="pepino/tablas/1.html"), name='tablas2Pep'),
    path('tablas3Pep/', TemplateView.as_view(template_name="pepino/tablas/3.html"), name='tablas3Pep'),
    path('graficasPep/', TemplateView.as_view(template_name="pepino/graficas/1.html"), name='graficas1Pep'),
    path('graficas2Pep/', TemplateView.as_view(template_name="pepino/graficas/2.html"), name='graficas2Pep'),
    path('tablas4Pep/', TemplateView.as_view(template_name="pepino/tablas/4.html"), name='tablas4Pep'),
    path('tablas5Pep/', TemplateView.as_view(template_name="pepino/tablas/5.html"), name='tablas5Pep'),
    path('graficas3Pep/', TemplateView.as_view(template_name="pepino/graficas/3.html"), name='graficas3Pep'),
    path('graficas4Pep/', TemplateView.as_view(template_name="pepino/graficas/4.html"), name='graficas4Pep'),
    path('iframePep/', TemplateView.as_view(template_name="pepino/iframe_de_todo.html"), name='iframePep'),
    path('pepino/', TemplateView.as_view(template_name="pepino/estadisticas_pepino.html"), name='pepino'),
    path('descripcion_pin/', TemplateView.as_view(template_name="piña/descripcion_piña.html"), name='descripcion_pin'),
    path('tablas1Pin/', TemplateView.as_view(template_name="piña/tablas/1.html"), name='tablas1Pin'),
    path('tablas2Pin/', TemplateView.as_view(template_name="piña/tablas/2.html"), name='tablas2Pin'),
    path('tablas3Pin/', TemplateView.as_view(template_name="piña/tablas/3.html"), name='tablas3Pin'),
    path('graficas1Pin/', TemplateView.as_view(template_name="piña/graficas/1.html"), name='graficas1Pin'),
    path('graficas2Pin/', TemplateView.as_view(template_name="piña/graficas/2.html"), name='graficas2Pin'),
    path('tablas4Pin/', TemplateView.as_view(template_name="piña/tablas/4.html"), name='tablas4Pin'),
    path('graficas3Pin/', TemplateView.as_view(template_name="piña/graficas/3.html"), name='graficas3Pin'),
    path('graficas4Pin/', TemplateView.as_view(template_name="piña/graficas/4.html"), name='graficas4Pin'),
    path('tablas5Pin/', TemplateView.as_view(template_name="piña/tablas/5.html"), name='tablas5Pin'),
    path('iframePin/', TemplateView.as_view(template_name="piña/iframe_de_todo.html"), name='iframePin'),
    path('pina/', TemplateView.as_view(template_name="piña/estadisticas_piña.html"), name='pina'),
    path('descripcion_pla/', TemplateView.as_view(template_name="platano/descripcion_platano.html"), name='descripcion_pla'),
    path('tablas1Pla/', TemplateView.as_view(template_name="platano/tablas/1.html"), name='tablas1Pla'),
    path('tablas2Pla/', TemplateView.as_view(template_name="platano/tablas/2.html"), name='tablas2Pla'),
    path('tablas3Pla/', TemplateView.as_view(template_name="platano/tablas/3.html"), name='tablas3Pla'),
    path('tablas4Pla/', TemplateView.as_view(template_name="platano/tablas/4.html"), name='tablas4Pla'),
    path('graficas1Pla/', TemplateView.as_view(template_name="platano/graficas/1.html"), name='graficas1Pla'),
    path('graficas2Pla/', TemplateView.as_view(template_name="platano/graficas/2.html"), name='graficas2Pla'),
    path('tablas5Pla/', TemplateView.as_view(template_name="platano/tablas/5.html"), name='tablas5Pla'),
    path('graficas3Pla/', TemplateView.as_view(template_name="platano/graficas/3.html"), name='graficas3Pla'),
    path('graficas4Pla/', TemplateView.as_view(template_name="platano/graficas/4.html"), name='graficas4Pla'),
    path('tablas6Pla/', TemplateView.as_view(template_name="platano/tablas/6.html"), name='tablas6Pla'),
    path('iframePla/', TemplateView.as_view(template_name="platano/iframe_de_todo.html"), name='iframePla'),
    path('platano/', TemplateView.as_view(template_name="platano/estadisticas_platano.html"), name='platano'),
    path('descripcion_san/', TemplateView.as_view(template_name="sandia/descripcion_sandia.html"), name='descripcion_san'),
    path('tablas1San/', TemplateView.as_view(template_name="sandia/tablas/1.html"), name='tablas1San'),
    path('tablas2San/', TemplateView.as_view(template_name="sandia/tablas/2.html"), name='tablas2San'),
    path('tablas3San/', TemplateView.as_view(template_name="sandia/tablas/3.html"), name='tablas3San'),
    path('graficas1San/', TemplateView.as_view(template_name="sandia/graficas/1.html"), name='graficas1San'),
    path('graficas2San/', TemplateView.as_view(template_name="sandia/graficas/2.html"), name='graficas2San'),
    path('tablas4San/', TemplateView.as_view(template_name="sandia/tablas/4.html"), name='tablas4San'),
    path('graficas3San/', TemplateView.as_view(template_name="sandia/graficas/3.html"), name='graficas3San'),
    path('graficas4San/', TemplateView.as_view(template_name="sandia/graficas/4.html"), name='graficas4San'),
    path('tablas5San/', TemplateView.as_view(template_name="sandia/tablas/5.html"), name='tablas5San'),
    path('iframeSan/', TemplateView.as_view(template_name="sandia/iframe_de_todo.html"), name='iframeSan'),
    path('sandia/', TemplateView.as_view(template_name="sandia/estadisticas_sandia.html"), name='sandia'),
    path('graficos-precios/', views.precios_maiz, name='graficos_precios'),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('directorio/', views.directorio, name='directorio'),
    path('ubicacion/', views.ubicacion, name='ubicacion'),





] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
